// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Trim and collapse whitespace-only or empty env values to undefined. */
function normalizeKey(value: string | undefined): string | undefined {
  return value?.trim() || undefined;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    process.env["SUPABASE_URL"] ||
    process.env["VITE_SUPABASE_URL"] ||
    "https://oltmnrkceodpyqznfhjb.supabase.co";
  // Prefer the project-scoped secret key; fall back to the legacy service-role key.
  // Neither value is ever exposed to VITE_ variables or client code.
  // Each candidate is trimmed individually so a whitespace-only preferred key
  // correctly falls through to a valid legacy key.
  const SUPABASE_ADMIN_KEY =
    normalizeKey(process.env["SVJ_SUPABASE_SECRET_KEY"]) ||
    normalizeKey(process.env["SUPABASE_SERVICE_ROLE_KEY"]);

  if (!SUPABASE_URL) {
    const message = `Missing Supabase environment variable(s): SUPABASE_URL. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Use the service-role key when available (bypasses RLS). In environments
  // like Lovable Cloud where the key is not set (reserved SUPABASE_ prefix),
  // fall back to the publishable key — queries will respect RLS, which is
  // acceptable because the auth middleware already attaches the user's own
  // bearer token. Privileged cross-user writes will fail at the RLS level
  // rather than crashing the entire server function chain.
  const serviceKey =
    SUPABASE_ADMIN_KEY ||
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    "sb_publishable_JbQU0vfJC2iQsnTg08N3XQ_hVBxK8DR";

  if (!SUPABASE_ADMIN_KEY) {
    console.warn(
      `[Supabase] Neither SVJ_SUPABASE_SECRET_KEY nor SUPABASE_SERVICE_ROLE_KEY is set. ` +
        `Using publishable key as fallback. Privileged RLS-bypassing operations will not work.`,
    );
  }

  return createClient<Database>(SUPABASE_URL, serviceKey, {
    global: {
      fetch: createSupabaseFetch(serviceKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

/**
 * Returns true when a privileged (service-role or secret) key is configured.
 * Privileged operations (account deletion, Plus grants) must check this
 * and fail closed when it returns false.
 *
 * Uses the same normalizeKey resolution as createSupabaseAdminClient so
 * production initialization and this guard cannot disagree.
 */
export function hasAdminKey(): boolean {
  return (
    !!normalizeKey(process.env["SVJ_SUPABASE_SECRET_KEY"]) ||
    !!normalizeKey(process.env["SUPABASE_SERVICE_ROLE_KEY"])
  );
}

/**
 * Throw a controlled error when no privileged key is configured.
 * Call this at the top of every server function that performs writes
 * requiring service_role bypass (Plus grants, code consumption, profile
 * mutations, account deletion).
 *
 * This is defence-in-depth: RLS and column-level triggers provide a
 * second safety net, but failing early with a clear message avoids
 * confusing database errors and makes misconfiguration obvious.
 */
export function requireAdminKey(): void {
  if (!hasAdminKey()) {
    throw new Error(
      "[Supabase] Privileged operation requires SVJ_SUPABASE_SECRET_KEY or " +
        "SUPABASE_SERVICE_ROLE_KEY. Neither is configured. Operation refused.",
    );
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
